### PR TITLE
ability to provide VPC region info

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot Parab <Prajyot.Parab1@ibm.com>

### CODE REVIEW

**Comment by Prajyot-Parab** [comment]
@mkumatag @Karthik-K-N 
Let me know if we are good to merge these changes post your validation checks.

**Comment by yussufsh** [comment]
Changes lgtm. I feel the caption should be changed as this pr is providing a way to pass classic region info and not fixing the auth.
Also an issue link with the explanation why we are doing the change will help others.

**Comment by mkumatag** [comment]
as far as I know there is nothing like region for the classic infra

**Comment by yussufsh** [comment]
> 
> 
> as far as I know there is nothing like region for the classic infra

@Prajyot-Parab Right we are dealing with VPC region and not classic. Please update the information and variable names.

**Comment by ssinha20** [comment]
@yussufsh @cs-zhang : Can you please help with review?

**Review by ssinha20 — DISMISSED** [review]
LGTM.

**Comment by ssinha20** [comment]
@Prajyot-Parab : Please let me know if we are good to close / anything is blocked?

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab : Please let me know if we are good to close / anything is blocked?

Updated branch to be inline with upstream repo - Good to merge now

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Review by ssinha20 — APPROVED** [review]
/lgtm

**Review by yussufsh — APPROVED** [review]
/lgtm

**Pull request merged**
