### PR TITLE
Add automated rhcos image file name markdown generator

### PR DESCRIPTION
**Pull request by yussufsh**

### CODE REVIEW

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm
/approve

**Comment by yussufsh** [comment]
/meow
@Rajalakshmi-Girish could you please check why this is not merging?

**Comment by Rajalakshmi-Girish** [comment]
@yussufsh This is not merging as we have change to .github/workflow.
Similar to https://github.com/ppc64le-cloud/pvsadm/pull/370

**Pull request merged**
