### PR TITLE
Update hashicorp null and random providers to enable darwin/arm64 support #451

### LINKED ISSUE #451: Update hashicorp null and random providers to enable darwin/arm64 support
# Background 
On darwin/arm64, I cloned and executed a `terraform init`. I encountered the following.

> ╷
> │ Error: Incompatible provider version
> │ 
> │ Provider registry.terraform.io/hashicorp/random v2.3.1 does not have a package
> │ available for your current platform, darwin_arm64.
> │ 
> │ Provider releases are separate from Terraform CLI releases, so not all providers are
> │ available for all platforms. Other versions of this provider may have different
> │ platforms supported.
> ╵
> 
> ╷
> │ Error: Incompatible provider version
> │ 
> │ Provider registry.terraform.io/hashicorp/null v2.1.2 does not have a package available
> │ for your current platform, darwin_arm64.
> │ 
> │ Provider releases are separate from Terraform CLI releases, so not all providers are
> │ available for all platforms. Other versions of this provider may have different
> │ platforms supported.
> ╵

Terraform added support for darwin/arm64. I updated hashicorp null and random providers locally, and it worked.

A composite of the version updates I had to make to pickup darwin/arm64. 

```
terraform {
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.4"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
  required_version = ">= 1.2.0"
}
```

If you'd like a PR raised, please let me know.

### PR DESCRIPTION
**Pull request by prb112**
- updated to enable support for darwin/arm64

Signed-off-by: Paul Bastide <pbastide@us.ibm.com>

Fixes #451

### CODE REVIEW

**Comment by prb112** [comment]
@yussufsh per issue #451 and the chat there, I have re-opened.

**Comment by yussufsh** [comment]
@prb112 could you please ammend your commit message mentioning the issue# you are trying to fix? Please read through our [pull-request-process](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/CONTRIBUTING.md#pull-request-process).

**Comment by prb112** [comment]
I have updated the body of the commit, previously only the title of the commit contained the reference.

**Review by yussufsh — APPROVED** [review]
/approve

**Comment by prb112** [comment]
Thank you so much, very helpful to have

**Pull request merged**
