### PR TITLE
Cluster upgrade using stable versions

### LINKED ISSUE #190: Image upgrade fails when providing the upgrade_image
console:
```
module.install.null_resource.upgrade[0]: Creating...
module.install.null_resource.upgrade[0]: Provisioning with 'file'...
module.install.null_resource.upgrade[0]: Provisioning with 'remote-exec'...
module.install.null_resource.upgrade[0] (remote-exec): Connecting to remote host via SSH...
module.install.null_resource.upgrade[0] (remote-exec):   Host: 169.48.X.X
module.install.null_resource.upgrade[0] (remote-exec):   User: root
module.install.null_resource.upgrade[0] (remote-exec):   Password: false
module.install.null_resource.upgrade[0] (remote-exec):   Private key: true
module.install.null_resource.upgrade[0] (remote-exec):   Certificate: false
module.install.null_resource.upgrade[0] (remote-exec):   SSH Agent: false
module.install.null_resource.upgrade[0] (remote-exec):   Checking Host Key: false
module.install.null_resource.upgrade[0] (remote-exec): Connected!
module.install.null_resource.upgrade[0] (remote-exec): Running ocp upgrade playbook...
module.install.null_resource.upgrade[0] (remote-exec): Using /root/ocp4-playbooks/ansible.cfg as config file
module.install.null_resource.upgrade[0] (remote-exec): [WARNING]: Found both group and host with same name: bootstrap

module.install.null_resource.upgrade[0] (remote-exec): PLAY [Upgrade OCP cluster] *****************************************************

module.install.null_resource.upgrade[0] (remote-exec): TASK [Gathering Facts] *********************************************************
module.install.null_resource.upgrade[0] (remote-exec): ok: [test-ocp-6f2c-bastion-0]

module.install.null_resource.upgrade[0] (remote-exec): TASK [include_role : ocp-upgrade] **********************************************
module.install.null_resource.upgrade[0] (remote-exec): fatal: [test-ocp-6f2c-bastion-0]: FAILED! => {"msg": "The conditional check 'upgrade_version != \"\"' failed. The error was: error while evaluating conditional (upgrade_version != \"\"): 'upgrade_version' is undefined\n\nThe error appears to be in '/root/ocp4-playbooks/playbooks/upgrade.yaml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - include_role:\n      ^ here\n"}

module.install.null_resource.upgrade[0] (remote-exec): PLAY RECAP *********************************************************************
module.install.null_resource.upgrade[0] (remote-exec): test-ocp-6f2c-bastion-0    : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0



Error: error executing "/tmp/terraform_1158875228.sh": Process exited with status 2


```

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #190

Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/192#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/release-4.6/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/192#pullrequestreview-556265304" title="LGTM">Prajyot-Parab</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/192#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/release-4.6/OWNERS)~~ [Prajyot-Parab,yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/192#pullrequestreview-556543088" title="LGTM">bpradipt</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/192#pullrequestreview-556265304" title="LGTM">Prajyot-Parab</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/192#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/release-4.6/OWNERS)~~ [Prajyot-Parab,bpradipt,yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
