### PR TITLE
Bump CSI Driver version to v0.1.1

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

### CODE REVIEW

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Review by yussufsh — APPROVED** [review]
/lgtm
@Prajyot-Parab note that we should not be changing for every minor release unless it is major or the previous one is having an issue. It is provided as a variable for that reason.

**Review by sajauddin — APPROVED** [review]

**Review by aishwaryabk — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
@Rajalakshmi-Girish ptal

**Comment by mkumatag** [comment]
It says the tide status as `In merge pool` that means it just satisfied with all the permissions required to merge, but wondering why it didn't merged!

image

**Pull request merged**
