### PR TITLE
Fix install module flow

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

### CODE REVIEW

**Comment by yussufsh** [comment]
@Prajyot-Parab did we test this?

**Comment by Prajyot-Parab** [comment]
> @Prajyot-Parab did we test this?

@aditijadhav38 update your test results here

**Comment by aditijadhav38** [comment]
@yussufsh Attaching complete logs of the cluster deployment
[prajyot-changes-cluster-logs.txt](https://github.com/ocp-power-automation/ocp4-upi-powervs/files/10012100/prajyot-changes-cluster-logs.txt)
Also we tested these changes with split commit 10f81375c43ccac751c632e876d05f0d4490e048
/cc @Prajyot-Parab

**Review by yussufsh — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
> @yussufsh Attaching complete logs of the cluster deployment [prajyot-changes-cluster-logs.txt](https://github.com/ocp-power-automation/ocp4-upi-powervs/files/10012100/prajyot-changes-cluster-logs.txt) Also we tested these changes with split commit 10f81375c43ccac751c632e876d05f0d4490e048

@aditijadhav38 thanks!

**Pull request merged**
