### PR TITLE
Update install.tf to use shallow clone

### PR DESCRIPTION
**Pull request by prb112**
git clone uses --quiet, yet it's deep clone.  Adding `--depth 1` improves performance a few hundred milliseconds difference in the time spent cloning, and long term it can avoid a superlinear increase in processing as the commit history grows.  Switching to a shallow clone improves performance about 100K difference in downloading ocp4-playbooks and 13M difference in downloading ocp4-helpernode.

Signed-off-by: Paul Bastide <pbastide@us.ibm.com>

### CODE REVIEW

**Comment by prb112** [comment]
> /lgtm /approve
> 
> @yussufsh @cs-zhang out of scope for this change - this always pulls the latest scripts and hard to predict the behaviour of the code, can we checkout a specific sha and keep bumping whenever we want to have better control?

I completely agree with your comment.  It's unversioned. It was a separate concern of mine.

**Comment by yussufsh** [comment]
/hold since this change is not tested.

@mkumatag  All the discussions above are in the scope of this change as we are already using a hash from released branches.
@prb112  We do `git checkout ${hash/branch}` just a line below. These changes do not suit the behavior of the script as it will fail to checkout after using clone with depth=1.
If we have any other way to directly checkout a single commit that would work but afaik `git clone` does not have such an option.

**Comment by mkumatag** [comment]
> /hold since this change is not tested.
> 
> @mkumatag All the discussions above are in the scope of this change as we are already using a hash from released branches. @prb112 We do `git checkout ${hash/branch}` just a line below. These changes do not suit the behavior of the script as it will fail to checkout after using clone with depth=1. If we have any other way to directly checkout a single commit that would work but afaik `git clone` does not have such an option.

valid concern, git checkout later in the code may not really work if you close with shallow..

**Comment by prb112** [comment]
> /hold since this change is not tested.
> 
> @mkumatag All the discussions above are in the scope of this change as we are already using a hash from released branches. @prb112 We do `git checkout ${hash/branch}` just a line below. These changes do not suit the behavior of the script as it will fail to checkout after using clone with depth=1. If we have any other way to directly checkout a single commit that would work but afaik `git clone` does not have such an option.

It's definitely cloning the whole repository then checking out the sha.  I'd recommend you do it in a single branch approach and combine the lines.  It's a really chatty way to do it. `--single-branch <SHA>`

**Comment by Rajalakshmi-Girish** [comment]
@prb112: PR is not mergeable.

<details>

The PR state is: BEHIND

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by prb112** [comment]
Feel free to close - as you mention the checkout is in a subsequent step.

**Pull request closed without merging**
