### PR TITLE
Allow global write access to 'storage_path'

### LINKED ISSUE #229: NFS storage mount restrictive permissions inhibit nfs-storage-provisioner
I provisioned from the `release-4.7` branch (at c98d7d6), and once the cluster was up the `deployment/image-registry` operator reported as degraded:

```
Cluster operator image-registry has been degraded for 10 minutes. Operator is degraded because Unavailable and cluster upgrades will be unstable.
```

```
status:
  conditions:
  - lastTransitionTime: "2021-03-03T13:52:28Z"
    lastUpdateTime: "2021-03-03T13:52:28Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
```

The `image-registry` wasn't able to get a `PersistentVolumeClaim`:
```
ocp-dal12-hub.ibm-power-acm.com > oc describe PersistentVolumeClaim/registry-pvc
Name:          registry-pvc
Namespace:     openshift-image-registry
StorageClass:  nfs-storage-provisioner
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: nfs-storage
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       image-registry-5dd46bcfb6-crccn
Events:
  Type     Reason                Age                    From                                                                                      Message
  ----     ------                ----                   ----                                                                                      -------
  Normal   ExternalProvisioning  3m34s (x331 over 83m)  persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "nfs-storage" or manually created by system administrator
  Normal   Provisioning          119s (x11 over 83m)    nfs-storage_nfs-client-provisioner-544bb74bd4-9tgxj_40e80696-59a2-417b-88c5-f4a4db4b5512  External provisioner is provisioning volume for claim "openshift-image-registry/registry-pvc"
  Warning  ProvisioningFailed    119s (x11 over 83m)    nfs-storage_nfs-client-provisioner-544bb74bd4-9tgxj_40e80696-59a2-417b-88c5-f4a4db4b5512  failed to provision volume with StorageClass "nfs-storage-provisioner": unable to create directory to provision new pv: mkdir /persistentvolumes/openshift-image-registry-registry-pvc-pvc-de4f6b47-fb49-4bb4-b996-669b8869d988: permission denied
```

Looks like a permissions issue, so I ssh'd into the bastion:
```
[root@ocp-dal12-hub-bastion-0 ~]# ls -ld /export/
drwxr-xr-x. 3 root root 4096 Mar  3 12:51 /export
[root@ocp-dal12-hub-bastion-0 ~]# chmod 777 /export/
[root@ocp-dal12-hub-bastion-0 ~]# ls -ld /export/
drwxrwxrwx. 3 root root 4096 Mar  3 12:51 /export/
```

And with the that `PersistenVolume` was created and `clusteroperator/image-registry` became available.

### PR DESCRIPTION
**Pull request by jaywcarman**
fixes #229

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/266#" title="Author self-approved">jaywcarman</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **yussufsh** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @yussufsh` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
Welcome @jaywcarman! It looks like this is your first PR to ocp-power-automation/ocp4-upi-powervs 🎉

**Comment by ltccci** [comment]
Hi @jaywcarman. Thanks for your PR.

I'm waiting for a [ocp-power-automation](https://github.com/orgs/ocp-power-automation/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/ocp-power-automation/ocp4-upi-powervs#contributing) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by bpradipt** [comment]
I'm wondering why we didn't face it earlier. 
@yussufsh @Prajyot-Parab any ideas ?

**Comment by jaywcarman** [comment]
I've seen the problem described in #229 several times, but not _every_ time I provision. I haven't figured out the underlying issue, but believe this patch is an effective fix.

Perhaps this is a clue: when the permissions are _not_ correct I've noticed that `root` still owns `/export`. Here's an example, after I've already run `chmod 777 /export`:
```
~ > ssh acm-spoke-47.mon01.ibm-power-acm.com 'ls -ld /export'    
drwxrwxrwx. 4 root root 4096 Apr 24 12:48 /export
```
But normally `/export` is owned by `nobody`. Here's an example of a bastion that did not have any problems:
```
~ > ssh acm-spoke-48.mon01.ibm-power-acm.com 'ls -ld /export'
drwxrwxrwx. 4 nobody nobody 4096 Apr 21 22:56 /export
~ > grep "^nobody" /etc/passwd
nobody:x:65534:65534:Kernel Overflow User:/:/sbin/nologin
```

Does the automation `chown /export` somewhere? If so that might be a good place to look.

**Comment by yussufsh** [comment]
> 
> Does the automation `chown /export` somewhere? If so that might be a good place to look.

This should be handled by the helpernode playbook. I see there is already a task to change it to `777` and `nobody:nobody`.

**Comment by jaywcarman** [comment]
@yussufsh is this the task you're looking at?
https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/tasks/main.yml#L173-L181

I don't think `ocp4-upi-powervs` logs any Ansible output does it? I can turn that on and see if I can capture output from this playbook when `root` still owns `/export`.

**Comment by yussufsh** [comment]
This is fixed in the latest code.

**Pull request closed without merging**
