### PR TITLE
ibm_dns_record to not use runtime value

### LINKED ISSUE #331: Invalid count argument in resource "ibm_dns_record" promps out when executing the command "openshift-install-powervs create"
I am following the guide(https://developer.ibm.com/tutorials/install-ocp-on-power-vs/) to install Red Hat OpenShift Container Platform 4.x on IBM Power Systems Virtual Servers. However the below error occurs. I select IBM Cloud Classic DNS and VPC Load Balancer services. Could you pls kindly have a look?

1. openshift-install-powervs create

```
[init_terraform] Initializing Terraform plugins and validating the code...
[apply] Running terraform apply... please wait
Error: Invalid count argument
  on modules/7_ibmcloud/dns.tf line 56, in resource "ibm_dns_record" "master":
  56:   count              = length(var.master_ips)
The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
Error: Invalid count argument
  on modules/7_ibmcloud/dns.tf line 65, in resource "ibm_dns_record" "worker":
  65:   count              = length(var.worker_ips)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

My configuration file is as below:
[var.tfvars.log](https://github.com/ocp-power-automation/ocp4-upi-powervs/files/7439125/var.tfvars.log)

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #331

### CODE REVIEW

**Review by rpsene — APPROVED** [review]

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Pull request merged**
