### PR TITLE
To remove the scp error with terraform v1.1.x

### PR DESCRIPTION
**Pull request by aishwaryabk**
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>

### CODE REVIEW

**Comment by yussufsh** [comment]
I think this fixes https://github.com/ocp-power-automation/ocp4-upi-powervs/issues/384
@aishwaryabk can you link this issue in your commit and this PR?

Also, can you explain the root cause on the issue and the fix implied? That will be helpful. Thanks.

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Review by yussufsh — APPROVED** [review]

**Comment by yussufsh** [comment]
Thanks @aishwaryabk 👍

**Comment by yussufsh** [comment]
@aishwaryabk you cannot cherrypick this automatically because you are using commit hash for ocp4-playbook from master. 
You will need to manually cherrypick and push those branches. Also, please consider picking other prs related to ansible & fips. This will not lead to conflict.

**Comment by aishwaryabk** [comment]
@yussufsh Thank you. I will manually cherrypick each PR.

**Comment by yussufsh** [comment]
@aishwaryabk @mkumatag @cs-zhang @Prajyot-Parab I feel multiple branch per branches is not helping for this and other related project. The code is same everywhere with same version of providers since release-4.6. Now I am not in favor of creating a new branch just for OCP 4.10.
I suggest keeping a single branch `main` going forward and tagging the versions whenever we have a breaking change. This way we won't need cherry-picking and creating branches for each release. Only issue is default variables pointing to correct OCP version and I think it can be handled with multiple versions of var.tfvars file.

**Comment by mkumatag** [comment]
> @aishwaryabk @mkumatag @cs-zhang @Prajyot-Parab I feel branch per release is not helping for this and other related project. The code is same everywhere with same version of providers since release-4.6. Now I am not in favor of creating a new branch just for OCP 4.10.
> I suggest keeping a single branch `main` going forward and tagging the versions whenever we have a breaking change. This way we won't need cherry-picking and creating branches for each release. Only issue is default variables pointing to correct OCP version and I think it can be handled with multiple versions of var.tfvars file.

My 2 cents:

I whole philosophy behind creating the different branches is that we maintain the code/instructions/docs for that individual releases, tags will be helpful but when we need to fix something on top of some tagged release it becomes too difficult.

wrt to cherry-pick, we shouldn't be cherry picking every damn thing(feature or bug) to the older version which doesn't make any sense to me unless it is a critical bug fix. And we should also revisit the support matrix often and also retire the branches which aren't used anymore.

This is all my opinion, I will leave the final decision to automation squad and @manojnkumar.

**Pull request merged**
