### PR TITLE
[Draft] added trigger for node count change and some checks in variables

### PR DESCRIPTION
**Pull request by Kuldip-Nanda**

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/142#" title="Author self-approved">Kuldip-Nanda</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **bpradipt** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @bpradipt` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
Welcome @Kuldip-Nanda! It looks like this is your first PR to ocp-power-automation/ocp4-upi-powervs 🎉

**Comment by ltccci** [comment]
Hi @Kuldip-Nanda. Thanks for your PR.

I'm waiting for a [ocp-power-automation](https://github.com/orgs/ocp-power-automation/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/ocp-power-automation/ocp4-upi-powervs#contributing) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by yussufsh** [comment]
@Kuldip-Nanda I do not understand how the worker CSR approvals will work? We do not want to run the full install process with nodes config install-config etc. In case users adding/removing nodes ocp4-playbooks should have a single role to approve CSR. Can we achieve that?

Second, please make validation changes into a new commit/PR. We already have an open PR for it.

**Comment by bpradipt** [comment]
@Kuldip-Nanda in addition to questions posed by @yussufsh can you please update the description with a high level overview of how the add node workflow is supposed to work ?

**Comment by bpradipt** [comment]
Thanks @Kuldip-Nanda.. I think this is better suited for `https://github.com/ocp-power-automation/ocp4-playbooks` 
@yussufsh  your thoughts please..

**Comment by yussufsh** [comment]
> @yussufsh your thoughts please..

Yes, it is better to update the install playbook with the same logic as you did in the shell script. This will help other TF projects use the same code piece.
You don't need to run all roles when cluster is already running and worker count is not same. Also use "nodes-config" role on all the new worker nodes.

**Comment by yussufsh** [comment]
Closing in favor of #156

**Pull request closed without merging**
