### PR TITLE
[release-4.6] Add doc for SNAT and update offload settings to be used

### PR DESCRIPTION
**Pull request by ltccci**
This is an automated cherry-pick of #262

/assign yussufsh

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/265#" title="Author self-approved">ltccci</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **bpradipt** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @bpradipt` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/release-4.6/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
@ltccci: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-ocp4-upi-powervs-terraform-fmt | a1f7bd2205bac6bfad1fd93cf55d1989fc17ad55 | [link](https://prow.ppc64le-cloud.org/view/s3/prow-logs/pr-logs/pull/ocp-power-automation_ocp4-upi-powervs/265/pull-ocp4-upi-powervs-terraform-fmt/1384009159527108608) | `/test pull-ocp4-upi-powervs-terraform-fmt`

[Full PR test history](https://prow.ppc64le-cloud.org/pr-history?org=ocp-power-automation&repo=ocp4-upi-powervs&pr=265). [Your PR dashboard](https://prow.ppc64le-cloud.org/pr?query=is:pr+state:open+author:ltccci).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ltccci** [comment]
@ltccci: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-ocp4-upi-powervs-terraform-fmt | a1f7bd2205bac6bfad1fd93cf55d1989fc17ad55 | [link](https://prow.ppc64le-cloud.org/view/s3/prow-logs/pr-logs/pull/ocp-power-automation_ocp4-upi-powervs/265/pull-ocp4-upi-powervs-terraform-fmt/1384009159527108608) | `/test pull-ocp4-upi-powervs-terraform-fmt`
pull-ocp4-upi-powervs-terraform-lint | a1f7bd2205bac6bfad1fd93cf55d1989fc17ad55 | [link](https://prow.ppc64le-cloud.org/view/s3/prow-logs/pr-logs/pull/ocp-power-automation_ocp4-upi-powervs/265/pull-ocp4-upi-powervs-terraform-lint/1384009159673909248) | `/test pull-ocp4-upi-powervs-terraform-lint`

[Full PR test history](https://prow.ppc64le-cloud.org/pr-history?org=ocp-power-automation&repo=ocp4-upi-powervs&pr=265). [Your PR dashboard](https://prow.ppc64le-cloud.org/pr?query=is:pr+state:open+author:ltccci).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by yussufsh — APPROVED** [review]

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/265#pullrequestreview-638994119" title="LGTM">bpradipt</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/265#" title="Author self-approved">ltccci</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/265#pullrequestreview-639504500" title="Approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/release-4.6/OWNERS)~~ [bpradipt,yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
