### PR TITLE
Use latest helpernode commit for ansible error

### LINKED ISSUE #455: Centos8 Bastion improperly updates to 2.13 causing error on install
# Summary
Centos8 Bastion improperly updates to 2.13 causing error

It looks like the `yum update` on [L344](https://github.com/ocp-power-automation/ocp4-upi-powervs/blame/master/modules/1_prepare/prepare.tf#L344)

Locking in to 

# Prerequisites 

1. Load a Centos8 image to PowerVS

```
cat /etc/redhat-release 
CentOS Stream release 8
```

2. Load an RHCOS image to PowerVS

# Reproducer Steps

1. Clone the primary branch of the powervs upi

```
$ git clone https://github.com/ocp-power-automation/ocp4-upi-powervs
```

3. Initialize the terraform 

```
$ terraform init
```

4. Setup the var.tfvars to point to a Centos8 stream image.

5. Run the apply 

#### Command

```
$ terraform apply -var-file=var.tfvars -no-color 
```

#### Output

```
module.install.null_resource.config (remote-exec): TASK [Enable restart always for critical services] *****************************
module.install.null_resource.config (remote-exec): fatal: [192.168.100.230]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: ['httpd', 'named', 'haproxy'] + [ 'dhcpd' ]. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}

module.install.null_resource.config (remote-exec): RUNNING HANDLER [restart bind] *************************************************

module.install.null_resource.config (remote-exec): RUNNING HANDLER [restart haproxy] **********************************************

module.install.null_resource.config (remote-exec): RUNNING HANDLER [restart httpd] ************************************************

module.install.null_resource.config (remote-exec): RUNNING HANDLER [restart dhcpd] ************************************************

module.install.null_resource.config (remote-exec): RUNNING HANDLER [restart nfs] **************************************************

module.install.null_resource.config (remote-exec): PLAY RECAP *********************************************************************
module.install.null_resource.config (remote-exec): 192.168.100.230            : ok=70   changed=50   unreachable=0    failed=1    skipped=75   rescued=0    ignored=0

╷
│ Error: remote-exec provisioner error
│ 
│   with module.install.null_resource.config,
│   on modules/5_install/install.tf line 221, in resource "null_resource" "config":
│  221:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_1797140775.sh": Process exited with status 2
```

As noted in [PR #300](https://github.com/redhat-cop/ocp4-helpernode/pull/300) a change to the list fixes the issue. 

6. Logging into the bastion and dump the detailed logs

#### Command

```
cd ocp4-helpernode && ansible-playbook -e @helpernode_vars.yaml tasks/main.yml -vvvv --become
```

I still hit the same issue. 

I checked the ansible-playbook version.

```
/usr/bin/ansible-playbook --version
ansible-playbook [core 2.13.5]
```

7. I replaced 2.13.5 with 2.12. 

```
$ yum remove ansible-core
$ yum install ansible-core-2.12.2-3.el8.ppc64le
```

8. The playbook passes with this version. 

```
META: ran handlers
Read vars_file '../vars/main.yml'
Read vars_file '../vars/ports.yml'
META: ran handlers

PLAY RECAP **************************************************************************************
192.168.100.230            : ok=88   changed=26   unreachable=0    failed=0    skipped=77   rescued=0    ignored=0   

[root@rdr-sec-squad-4d25-osa21-bastion-0 ocp4-helpernode]# echo $?
0
```

Further, I can lock the repo in with the Ansible Repo [https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/variables.tf#L323](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/variables.tf#L323) however I cannot lock in the version.

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #455

Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>

### CODE REVIEW

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by aishwaryabk — APPROVED** [review]
/lgtm

**Pull request merged**
