### PR TITLE
Update defaults and docs to latest stable OCP version

### PR DESCRIPTION
**Pull request by yussufsh**
Signed-off-by: Yussuf Shaikh <yussuf.shaikh1@ibm.com>

### CODE REVIEW

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Comment by yussufsh** [comment]
> New changes are detected. LGTM label has been removed.

Sorry I accidentally pushed another commit to this PR. @Prajyot-Parab please help with your approval again.

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Review by aishwaryabk — APPROVED** [review]
/lgtm

**Pull request merged**
