### PR TITLE
Auto set volume type from the RHEL and RHCOS images

### LINKED ISSUE #246: Use the bastion image storage_type for NFS volume
Below error is shown when using different storage type for data volume to be mounted to the bastion. The bastion VM storage type should be same as data volume storage type.

```
Error: failed to provision Failed to Create PVM Instance :[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances][400] pcloudPvminstancesPostBadRequest  &{Code:0 Description:bad request: calculated parameter has failed for cloud-instance dad1780f13c54b8a9f7ea55778e965e0: validate volume aec93135-6dd9-4117-ae69-3861e42f8bff failed, volume storage type tier3 does not match VM deployment storage type tier1 Error:bad request Message:}
```

We need to automatically read the storage_type set on the image to use for data volume.

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #246

Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/255#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by cs-zhang — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/255#pullrequestreview-625699756" title="LGTM">cs-zhang</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/255#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/255#pullrequestreview-625995650" title="LGTM">bpradipt</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/255#pullrequestreview-625699756" title="LGTM">cs-zhang</a>*, *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/255#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)~~ [bpradipt,yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ltccci** [comment]
@yussufsh: new pull request created: #256

<details>

In response to [this](https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/255#issuecomment-812336247):

>/cherrypick release-4.7


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by ltccci** [comment]
@yussufsh: #255 failed to apply on top of branch "release-4.6":
```
Applying: Auto set volume type from the RHEL and RHCOS images
Using index info to reconstruct a base tree...
M	docs/var.tfvars-doc.md
M	ocp.tf
M	var.tfvars
M	variables.tf
Falling back to patching base and 3-way merge...
Auto-merging variables.tf
CONFLICT (content): Merge conflict in variables.tf
Auto-merging var.tfvars
Auto-merging ocp.tf
Auto-merging docs/var.tfvars-doc.md
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Auto set volume type from the RHEL and RHCOS images
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

<details>

In response to [this](https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/255#issuecomment-812336790):

>/cherrypick release-4.6


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by ltccci** [comment]
@yussufsh: #255 failed to apply on top of branch "release-4.5":
```
Applying: Auto set volume type from the RHEL and RHCOS images
Using index info to reconstruct a base tree...
M	docs/var.tfvars-doc.md
M	modules/1_prepare/prepare.tf
M	modules/1_prepare/variables.tf
M	modules/4_nodes/nodes.tf
M	ocp.tf
M	var.tfvars
M	variables.tf
Falling back to patching base and 3-way merge...
Auto-merging variables.tf
CONFLICT (content): Merge conflict in variables.tf
Auto-merging var.tfvars
Auto-merging ocp.tf
Auto-merging modules/4_nodes/nodes.tf
Auto-merging modules/1_prepare/variables.tf
Auto-merging modules/1_prepare/prepare.tf
Auto-merging docs/var.tfvars-doc.md
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
Patch failed at 0001 Auto set volume type from the RHEL and RHCOS images
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

```

<details>

In response to [this](https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/255#issuecomment-812336819):

>/cherrypick release-4.5


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
