### PR TITLE
Add RHCOS kernel options before installation

### PR DESCRIPTION
**Pull request by aishwaryabk**
Signed-off-by: Aishwarya Kamat <aishwarya.kamat@ibm.com>

### CODE REVIEW

**Comment by yussufsh** [comment]
Why do we pre-kernel options? We should be good to use the existing options variable and set it anytime (before/after) install, It is one and the same thing.

**Review by yussufsh — CHANGES_REQUESTED** [review]
Please update the `install_playbook_tag` value to the latest commit hash, otherwise these changes won't work.

**Review by yussufsh — APPROVED** [review]

**Review by Prajyot-Parab — APPROVED** [review]
/approve

**Pull request merged**
