### PR TITLE
Update IBM Cloud services authentication

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot Parab <Prajyot.Parab1@ibm.com>

### CODE REVIEW

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by Prajyot-Parab** [comment]
> Can I know the the requirement and reason for this PR? An issue would help.
> What is "apikey"?

we can use -
```
iaas_classic_username = "apikey"
iaas_classic_api_key = <ibm_cloud_api_key>

```
Then we don't need additional/diff credentials to authenticate against classic services. This way we can use the ibmcloud apikey itself for classic as well.

cc- @bpradipt @mkumatag

**Comment by yussufsh** [comment]
> > Can I know the the requirement and reason for this PR? An issue would help.
> > What is "apikey"?
> 
> we can use -
> 
> ```
> iaas_classic_username = "apikey"
> iaas_classic_api_key = <ibm_cloud_api_key>
> ```
> 
> Then we don't need additional/diff credentials to authenticate against classic services. This way we can use the ibmcloud apikey itself for classic as well.
> 
> cc- @bpradipt @mkumatag

Then should not we remove the variables and automate it altogether?

**Comment by yussufsh** [comment]
I will leave it upto you to decide if we want to retain or remove the classic author vars. If we are keeping it then better mention it clearly in doc that this is optional and can be used only when using a different account/api key, otherwise ibmcloud api key will be used. 
Thanks.

**Comment by bpradipt** [comment]
> > > Can I know the the requirement and reason for this PR? An issue would help.
> > > What is "apikey"?
> > 
> > 
> > we can use -
> > ```
> > iaas_classic_username = "apikey"
> > iaas_classic_api_key = <ibm_cloud_api_key>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then we don't need additional/diff credentials to authenticate against classic services. This way we can use the ibmcloud apikey itself for classic as well.
> > cc- @bpradipt @mkumatag
> 
> Then should not we remove the variables and automate it altogether?

Let the variables be there for now. Setting the default to use ibmcloud api key should be fine.

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by yussufsh — APPROVED** [review]
/lgtm

**Pull request merged**
