### PR TITLE
docs: add ibmcloud cli info

### PR DESCRIPTION
**Pull request by clnperez**
Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/74#" title="Author self-approved">clnperez</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **prajyot-parab**
You can assign the PR to them by writing `/assign @prajyot-parab` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by clnperez** [comment]
This link is helpful because it shows the cli install link, the plugin install command, and the cloud login command. So let's definitely include this in the doc.

**Comment by clnperez** [comment]
n/m. this is in the README and i was looking in the wrong place. closing.

**Pull request closed without merging**
