### PR TITLE
Increase the default memory for master nodes

### PR DESCRIPTION
**Pull request by yussufsh**
Signed-off-by: Yussuf Shaikh <yussuf.shaikh@ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/159#" title="Author self-approved">yussufsh</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Focp4-upi-powervs).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/OWNERS)~~ [yussufsh]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sudeeshjohn — APPROVED** [review]
/lgtm

**Review by bpradipt — COMMENTED** [review]
/lgtm

**Review by bpradipt — APPROVED** [review]

**Comment by yussufsh** [comment]
@mkumatag could you please check why lgtm label is not added?

**Comment by mkumatag** [comment]
> @mkumatag could you please check why lgtm label is not added?

This is because of the reason - https://github.ibm.com/powercloud/container-dev/issues/1359

**Comment by mkumatag** [comment]
retry
/lgtm

**Pull request merged**
